"""Module that defines constants.
"""
NEGATIVE_SAMPLING_METHOD_UNIFORM = 'uniform'
NEGATIVE_SAMPLING_METHOD_TYPE = 'type'
NEGATIVE_SAMPLING_METHOD_SIMILARITY = 'similarity'
NEGATIVE_SAMPLING_METHOD_EGO_NETWORK_COUNT = 'count'
NEGATIVE_SAMPLING_METHOD_EGO_NETWORK_JACCARD = 'jaccard'
NEGATIVE_SAMPLING_METHODS = [NEGATIVE_SAMPLING_METHOD_UNIFORM, NEGATIVE_SAMPLING_METHOD_TYPE, NEGATIVE_SAMPLING_METHOD_SIMILARITY, NEGATIVE_SAMPLING_METHOD_EGO_NETWORK_COUNT, NEGATIVE_SAMPLING_METHOD_EGO_NETWORK_JACCARD]

EGO_NETWORK_MODES = [NEGATIVE_SAMPLING_METHOD_EGO_NETWORK_COUNT, NEGATIVE_SAMPLING_METHOD_EGO_NETWORK_JACCARD]
